version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "omniapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dl2049ju1h24"
s3_prefix = "omniapi"
region = "us-east-1"
profile = "ann04-sandbox-poweruser"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=091021251638.dkr.ecr.us-east-1.amazonaws.com/omniapi"]

