
openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
#servers:
#  - url: http://localhost:9090/v1.0

paths:
  /hello:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: app.post_greeting
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello dave!"
  /hello2:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: app.post_greeting2
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello dave!"